// Egypt governorates list (static — names only; fees live in admin Settings).
export const EG_CITIES = [
  "Cairo",
  "Giza",
  "Qalyubia",
  "Alexandria",
  "Beheira",
  "Gharbia",
  "Dakahlia",
  "Damietta",
  "Kafr El Sheikh",
  "Sharqia",
  "Monufia",
  "Port Said",
  "Ismailia",
  "Suez",
  "Fayoum",
  "Beni Suef",
  "Minya",
  "Asyut",
  "Sohag",
  "Qena",
  "Luxor",
  "Aswan",
  "Red Sea",
  "Matrouh",
  "New Valley",
  "North Sinai",
  "South Sinai",
] as const;
